name: terraform

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5  # match your local version

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Export Terraform outputs to GitHub Secrets
        run: |
          gh secret set AZURE_REGISTRY_NAME --body "$(terraform output -raw acr_name)"
          gh secret set AKS_CLUSTER_NAME --body "$(terraform output -raw aks_name)"
          gh secret set AKS_RESOURCE_GROUP --body "$(terraform output -raw resource_group_name)"
          gh secret set VNET_NAME --body "$(terraform output -raw vnet_name)"
          gh secret set SUBNET_NAME --body "$(terraform output -raw subnet_name)"
#small comment here for test 
