name: terraform

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production # Optional but good practice.
    defaults:
      run:
        shell: bash
        working-directory: ./terraform # Set working directory once for all steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # This step just prints the critical output for you to manually copy
      - name: Output Critical Values
        run: |
          echo "ACR Name: $(terraform output -raw acr_name)"
          echo "AKS Name: $(terraform output -raw aks_name)"
          echo "Resource Group: $(terraform output -raw resource_group_name)"
